
* dotfiles

A project for managing all important dotfiles in home directory. It only contains the 
sources of my configuration. All other libraries and dependencies are install via scripts
under *pkgs/*

** install

1. run all scripts in ./pkgs in the order of their prefixes
2. run ./setup.sh
3. source .zshrc

** Packages

All the packages need to be installed separately before running the *setup.sh* script.

*** oh-my-zsh
A great framework for managing *zsh* configuration.

Project Link: github.com/robbyrussell/oh-my-zsh

*** zsh-syntax-highlighting
A package that provides syntax highlighting for *zsh*.

Project Link: github.com/zsh-users/zsh-syntax-highlighting

** unintall

1. ./revert.sh

** Dot Files
   
*** Emacs
**** List of Packages
1. Magit
2. helm
3. org
4. smex
5. flycheck
6. pdf-tools
7. auto-complete
8. solidity-mode
9. yasnippet
10. yasnippet-snippets
11. exec-path-from-shell
12. color-theme-sanitynic-tomorrow

**** Add to Package List
Add the package's name to 'pkg-list' in init.el and reload emacs

